// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace messages
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class CCAuthorization : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"CCAuthorization\",\"namespace\":\"messages\",\"fields\":[{\"name" +
				"\":\"provider\",\"type\":\"string\"},{\"name\":\"ccnumber\",\"type\":\"string\"},{\"name\":\"statu" +
				"s\",\"type\":\"string\"}]}");
		private string _provider;
		private string _ccnumber;
		private string _status;
		public virtual Schema Schema
		{
			get
			{
				return CCAuthorization._SCHEMA;
			}
		}
		public string provider
		{
			get
			{
				return this._provider;
			}
			set
			{
				this._provider = value;
			}
		}
		public string ccnumber
		{
			get
			{
				return this._ccnumber;
			}
			set
			{
				this._ccnumber = value;
			}
		}
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.provider;
			case 1: return this.ccnumber;
			case 2: return this.status;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.provider = (System.String)fieldValue; break;
			case 1: this.ccnumber = (System.String)fieldValue; break;
			case 2: this.status = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
