# FROM  mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim
FROM mcr.microsoft.com/dotnet/core/sdk:3.0
WORKDIR /app
COPY consumer/consumer.csproj consumer/
COPY messages/messages.csproj messages/
RUN dotnet restore consumer/consumer.csproj
COPY . .
WORKDIR /app/consumer
CMD dotnet run